In [195]:
# pip install numpy
import numpy as np
print(np.__version__)

1.26.4


In [11]:
arr  = np.array([3,4,4.5,5])
arr
# type(arr)

array([3. , 4. , 4.5, 5. ])

In [192]:
np.random.rand(2,
               2,3)
np.random.seed(3)
np.random.rand()

0.5507979025745755

In [197]:

arr_num = np.array([1, 2, 3, 4])
print(arr_num .dtype)
arr_fruit = np.array(['apple', 'banana', 'cherry'])
print(arr_fruit .dtype)

int32
<U6


In [199]:
arr = np.array([1, 0, 3])
newarr_2 = arr.astype(bool)
print(newarr_2 , arr)
print(newarr_2.dtype)

[ True False  True] [1 0 3]
bool


In [206]:
original_array = np.array([7, 8, 9])
# Creating a view using slicing
sliced_array = original_array[:2]
print(sliced_array)
# Creating a view using indexing
indexed_array = original_array[[0,2]]
print(indexed_array)

[7 8]
[7 9]


In [207]:
original_array = np.array([[22, 23, 24], [25, 26, 27]])
view_array = original_array[:, 1:]
print(view_array)

[[23 24]
 [26 27]]


In [219]:
original_array = np.array([7, 8, 9,4 ,2 ,2 ,3,4])
print(original_array.view().reshape(2,2,2))

[[[7 8]
  [9 4]]

 [[2 2]
  [3 4]]]


In [222]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])
print(np.concatenate((array1,array2.T),axis = 1))

[[1 2 5]
 [3 4 6]]


In [232]:
arange_array = np.logspace(0,50,100)
print(arange_array)

[1.00000000e+00 3.19926714e+00 1.02353102e+01 3.27454916e+01
 1.04761575e+02 3.35160265e+02 1.07226722e+03 3.43046929e+03
 1.09749877e+04 3.51119173e+04 1.12332403e+05 3.59381366e+05
 1.14975700e+06 3.67837977e+06 1.17681195e+07 3.76493581e+07
 1.20450354e+08 3.85352859e+08 1.23284674e+09 3.94420606e+09
 1.26185688e+10 4.03701726e+10 1.29154967e+11 4.13201240e+11
 1.32194115e+12 4.22924287e+12 1.35304777e+13 4.32876128e+13
 1.38488637e+14 4.43062146e+14 1.41747416e+15 4.53487851e+15
 1.45082878e+16 4.64158883e+16 1.48496826e+17 4.75081016e+17
 1.51991108e+18 4.86260158e+18 1.55567614e+19 4.97702356e+19
 1.59228279e+20 5.09413801e+20 1.62975083e+21 5.21400829e+21
 1.66810054e+22 5.33669923e+22 1.70735265e+23 5.46227722e+23
 1.74752840e+24 5.59081018e+24 1.78864953e+25 5.72236766e+25
 1.83073828e+26 5.85702082e+26 1.87381742e+27 5.99484250e+27
 1.91791026e+28 6.13590727e+28 1.96304065e+29 6.28029144e+29
 2.00923300e+30 6.42807312e+30 2.05651231e+31 6.57933225e+31
 2.10490414e+32 6.734150

In [233]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [234]:
a = np.array([1,3,4,5,6,8])
print(a[a%2==0])

[4 6 8]


In [243]:
arr_3d = np.arange(24).reshape(2, 3, 4)

# Slicing along both dimensions

sliced_array = arr_3d[:, 1:3, 2]
print(arr_3d)

print(sliced_array)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 6 10]
 [18 22]]


In [244]:
arr_3d = np.random.rand(2, 3, 4)
arr_3d

array([[[0.78031476, 0.30636353, 0.22195788, 0.38797126],
        [0.93638365, 0.97599542, 0.67238368, 0.90283411],
        [0.84575087, 0.37799404, 0.09221701, 0.6534109 ]],

       [[0.55784076, 0.36156476, 0.2250545 , 0.40651992],
        [0.46894025, 0.26923558, 0.29179277, 0.4576864 ],
        [0.86053391, 0.5862529 , 0.28348786, 0.27797751]]])